require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec


#################### Layout ####################################################


Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_block

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented_relative_to_receiver


#################### Style #####################################################


Style/Documentation:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInBlockArgs:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma


#################### Naming ####################################################

Naming/VariableNumber:
  Enabled: false

#################### Metrics ###################################################


Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false


#################### Rails #####################################################


Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

#################### RSpec #####################################################


RSpec/ExampleLength:
  Enabled: false


#################### Global Exclusions #########################################


AllCops:
  Exclude:
    - db/schema.rb
    - db/datawarehouse_schema.rb
